FROM python:3.12-alpine
RUN pip install --no-cache-dir boto3
RUN mkdir -p /bootstrap
COPY bootstrap.py create-execution-queue.json create-worker-nodes.json /bootstrap/
WORKDIR /bootstrap
ENTRYPOINT ["python", "/bootstrap/bootstrap.py"]
